# Generated by Django 3.1.5 on 2021-09-22 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_time',
            field=models.DateTimeField(db_column='timestamp', default=datetime.datetime(2021, 9, 22, 12, 10, 41, 824159)),
        ),
    ]
