# Generated by Django 3.1.5 on 2021-09-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, db_column='timestamp'),
        ),
    ]
